-- AlterTable
ALTER TABLE "BoothInstance" ADD COLUMN IF NOT EXISTS "windowsPrinterName" TEXT;
ALTER TABLE "BoothInstance" ADD COLUMN IF NOT EXISTS "printBridgeUrl" TEXT DEFAULT 'http://127.0.0.1:39100';
ALTER TABLE "BoothInstance" ADD COLUMN IF NOT EXISTS "maxPhotoVariants" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "selectedCaptureId" TEXT;
ALTER TABLE "Capture" ADD COLUMN IF NOT EXISTS "sequenceIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AiJob" ADD COLUMN IF NOT EXISTS "shareToken" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "AiJob_shareToken_key" ON "AiJob"("shareToken");
